[package]
name = "vel0city"
version = "0.0.1"
build = "build.rs"

[dependencies.nalgebra]
git = "https://github.com/jpernst/nalgebra"

[dependencies.capnp]
git = "https://github.com/dwrensha/capnproto-rust"

[build-dependencies.capnpc]
git = "https://github.com/dwrensha/capnpc-rust"

[dependencies.wavefront_obj]
git = "https://github.com/PistonDevelopers/wavefront_obj"

[dependencies.glium]
git = "https://github.com/tomaka/glium"
features = ["nalgebra"]

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

[dependencies.glium_macros]
git = "https://github.com/tomaka/glium"

[dependencies]
rustc-serialize = "*"
time = "*"

#[dependencies.ncollide]
#git = "https://github.com/sebcrozet/ncollide"
