[package]
name = "vel0city"
version = "0.0.1"
build = "build.rs"

[dependencies.obj]
git = "https://github.com/csherratt/obj"
 
[dependencies.gfx]
git = "http://github.com/gfx-rs/gfx-rs"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.capnp]
git = "https://github.com/dwrensha/capnproto-rust"

[build-dependencies.capnpc]
git = "https://github.com/dwrensha/capnpc-rust"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"
default-features = false

#[dependencies.ncollide]
#git = "https://github.com/sebcrozet/ncollide"
